### ISSUE TITLE
Use streams in write property operation on browsers

### ISSUE THREAD

**Issue by relu91** [eclipse/thingweb.node-wot#790]
I've created this issue mostly to monitor the two issues that I linked below. 
> After plumbing into the inner workings of broserify and the Web platform, I've found that sadly stream upload is not supported for browsers. This means that we can't use a stream to write properties or invoke actions.  Solving this issue is going to be tricky but I hope to find a patch that will only be active on browser environments. 

For the ones that are curious. Here are the relevant issues:
https://github.com/whatwg/fetch/issues/1438 
https://bugs.chromium.org/p/chromium/issues/detail?id=688906

_Originally posted by @relu91 in https://github.com/eclipse/thingweb.node-wot/issues/785#issuecomment-1169744324_

**Comment by samubura** [comment]
I'm having issues using the browser bundle to invoke actions
the error I get is:

    TypeError: stream_1.Readable.from is not a function
    valueToContent https://cdn.jsdelivr.net/npm/@node-wot/browser-bundle@0.8.1/dist/wot-bundle.min.js:49981
    invokeAction https://cdn.jsdelivr.net/npm/@node-wot/browser-bundle@0.8.1/dist/wot-bundle.min.js:49762
    __awaiter https://cdn.jsdelivr.net/npm/@node-wot/browser-bundle@0.8.1/dist/wot-bundle.min.js:49326
    __awaiter https://cdn.jsdelivr.net/npm/@node-wot/browser-bundle@0.8.1/dist/wot-bundle.min.js:49322
    invokeAction https://cdn.jsdelivr.net/npm/@node-wot/browser-bundle@0.8.1/dist/wot-bundle.min.js:49747`
    
is this related to this issue?

**Comment by danielpeintner** [comment]
The issue was resolved by https://github.com/eclipse/thingweb.node-wot/pull/809.

This was done on 27 July and no more release has been published since than. I hope we can publish a *new* release soon. In the meantime you may want to use `wot-bundle.min.js` from a master build.

**Comment by relu91** [comment]
The new release is out, @samubura can you confirm that you don't experience that issue anymore?

**Comment by samubura** [comment]
Yes! I can confirm it is working as expected now.

**Comment by relu91** [comment]
The tracked issue is now resolved, but the landscape is not really consistent. Check this [report](https://staging.wpt.fyi/results/fetch/api/basic/request-upload.any.html?label=experimental&label=master&aligned)

**Comment by relu91** [comment]
Note that there is mentioned that stream upload is not supposed to work with HTTP/1.1 (I believe I read somewhere on the fetch standard that this is prohibited but allowed by HTTP protocol 🤔 - that's why in some JS runtime is possible to use streams in HTTP Post requests on HTTP1.1).
